import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // SilkSoul material design tokens (from DESIGN.md + style.md)
        background: "#faf9f6",
        onBackground: "#1a1c1a",
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#444748",
        "surface-variant": "#e3e2e0",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        secondary: "#725b2f",
        "on-secondary": "#ffffff",
        "secondary-container": "#fcdba4",
        "on-secondary-container": "#775f33",
        "secondary-fixed": "#ffdea7",
        "on-secondary-fixed": "#271900",
        "secondary-fixed-dim": "#e1c28d",
        onSecondaryFixedVariant: "#58431a",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#151e10",
        "on-tertiary-container": "#7c8773",
        "tertiary-fixed": "#dbe6cf",
        "on-tertiary-fixed": "#151e10",
        "tertiary-fixed-dim": "#bfcab4",
        error: "#a65b5b",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        // Brand accents (from style.md)
        gold: "#B69A68",
        "muted-sage": "#78836F",
        "warm-white": "#FAF9F6",
        "warm-cream": "#F3F0EA",
        charcoal: "#171717",
        "text-secondary": "#66635F",
        "text-muted": "#96918A",
        border: "#E3DFD8",
        success: "#5F8065",
        warning: "#B28A50",
        info: "#68798A",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Georgia", "serif"],
        sans: ["var(--font-jakarta)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em" }],
        "display-hero-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em" }],
        "headline-sm": ["22px", { lineHeight: "30px" }],
        "title-editorial": ["18px", { lineHeight: "26px", letterSpacing: "0.01em" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.005em" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.12em" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 20px -2px rgba(23, 23, 23, 0.03), 0 1px 4px -1px rgba(23, 23, 23, 0.02)",
        hover: "0 12px 32px -4px rgba(23, 23, 23, 0.06), 0 2px 8px -2px rgba(23, 23, 23, 0.03)",
        overlay: "0 24px 48px -12px rgba(23, 23, 23, 0.12)",
      },
      maxWidth: {
        content: "1440px",
      },
      spacing: {
        "2xs": "0.25rem",
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
        "3xl": "4.5rem",
        "4xl": "6rem",
        "5xl": "8rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "5rem",
      },
    },
  },
  plugins: [],
};

export default config;
